apiVersion: v2
name: woodpecker-agent
description: A Helm chart for the Woodpecker agent
type: application
version: 0.0.0
appVersion: "0.0.0"
keywords:
- continuous-delivery
- continuous-deployment
- continuous-integration
- docker
- go
sources:
- https://github.com/woodpecker-ci/woodpecker
maintainers:
- name: Laszlo Fogas
  email: laszlo@laszlo.cloud
