matrix:
  include:
    - CHART_NAME: woodpecker-agent
    - CHART_NAME: woodpecker-server

variables:
  - &when_path
    - "charts/${CHART_NAME}"
    - ".woodpecker/helm.yml"

pipeline:
  set-version:
    image: alpine/helm:3.5.3
    commands:
      - export APP_VERSION="${CI_COMMIT_TAG##v}"
      - export APP_VERSION=$${CHART_VERSION:=0.0.0}
      - echo "AppVersion $APP_VERSION"
      - sed -i "s/<version>/$APP_VERSION/g" charts/${CHART_NAME}/Chart.yaml
      - cat charts/${CHART_NAME}/Chart.yaml
    when:
      path: *when_path

  lint:
    image: alpine/helm:3.5.3
    commands:
      - helm lint charts/${CHART_NAME}/
    when:
      path: *when_path

  pre-check:
    image: alpine/git
    commands:
      - git fetch --all -v
      - CHART_VERSION=$(awk '/^version:.*/ { print $2 }' charts/${CHART_NAME}/Chart.yaml)
      - LAST_VERSION=$(git diff master charts/${CHART_NAME}/Chart.yaml| grep -E '^-version:')
      - |
        if [ -z "${LAST_VERSION}"] || [  "${CHART_VERSION}" == "$(echo -e "${CHART_VERSION}\n${LAST_VERSION}" | sort -V | head -n1)" ] ; then
          echo "Chart Version has not been bumped! (${CHART_VERSION} vs. ${LAST_VERSION})"
          exit 1
        fi
    when:
      path: *when_path

  release:
    image: quay.io/helmpack/chart-releaser:v1.4.0
    secrets:
      - source: github_token
        target: CR_TOKEN
    commands:
      - git config --global user.email "woodpecker-bot@obermui.de"
      - git config --global user.name "woodpecker-bot"
      - mkdir -p .cr-index
      - cr package charts/${CHART_NAME}
      - cr upload --owner woodpecker-ci --git-repo woodpecker-ci.github.io --release-name-template "helm-{{ .Name }}-{{ .Version }}"
      - git clone https://github.com/woodpecker-ci/woodpecker-ci.github.io.git
      - cd woodpecker-ci.github.io/ && cr index --owner woodpecker-ci --git-repo woodpecker-ci.github.io --pages-branch master --package-path ../.cr-release-packages --index-path ../.cr-index/index.yaml --charts-repo https://woodpecker-ci.org --push --release-name-template "helm-{{ .Name }}-{{ .Version }}"
    when:
      branch: master
      path: *when_path
